import { faker } from "@faker-js/faker"; // import faker
export const mockUserCredentials: userDetail[] = [
  {
    firstTimeOnboard: true,
    email: "1@gmail.com",
    password: "123123123",
    firstName: "Zhenjie",
    lastName: "Liang",
    $id: "1",
  },
];

const companies = [
  "Walmart",
  "Target",
  "Walgreens",
  "Kroger",
  "Safeway",
  "Rite Aid",
  "Aldi",
  "Trader Joe's",
  "Costco",
  "Sam's Club",
  "Publix",
  "Albertsons",
  "Meijer",
  "H-E-B",
  "WinCo Foods",
  "Hy-Vee",
  "BJ's Wholesale Club",
  "Sprouts Farmers Market",
  "The Fresh Market",
  "Wegmans",
  "Giant Eagle",
  "Stop & Shop",
  "ShopRite",
  "Harris Teeter",
  "Food Lion",
  "Piggly Wiggly",
  "Save-A-Lot",
  "Price Chopper",
  "Hannaford",
  "Ingles Markets",
  "Weis Markets",
  "Food City",
  "SuperValu",
  "Raley's",
  "Tops Friendly Markets",
  "King Soopers",
  "Fry's",
  "Smith's",
  "Fred Meyer",
  "Vons",
  "Ralphs",
  "Jewel-Osco",
  "Shaw's",
  "Acme Markets",
  "Giant Food",
  "Food 4 Less",
  "Stater Bros.",
  "Smart & Final",
  "Bashas'",
  "Central Market",
  "Brookshire's",
  "Foodtown",
  "Gelson's Markets",
  "Lucky Supermarkets",
  "Market Basket",
  "Fareway",
  "Festival Foods",
  "Reasor's",
  "Win-Dixie",
  "Bi-Lo",
  "Redner's Markets",
  "Schnucks",
  "Cub Foods",
  "Fresh Thyme Market",
  "Thriftway",
  "United Supermarkets",
  "Lowes Foods",
  "El Super",
  "Superior Grocers",
  "Grocery Outlet",
  "Marc's",
  "Metro Market",
  "FreshDirect",
  "PCC Community Markets",
  "Sprouts",
  "Earth Fare",
  "Fresh & Easy",
  "Mariano's",
  "Fairway Market",
  "Whole Earth Center",
  "MOM's Organic Market",
  "Earth Origins Market",
  "GreenWise Market",
  "Lucky's Market",
  "New Seasons Market",
  "Erewhon Market",
  "Natural Grocers",
  "Bristol Farms",
  "Amazon Fresh",
  "Fresh Market",
  "Central Market",
  "Macey's",
  "Scolari's Food and Drug",
  "Harmons",
  "Market of Choice",
  "Metropolitan Market",
  "Leevers Supermarkets",
  "Milam's Markets",
  "H Mart",
  "99 Ranch Market",
];

const numTimes = [
  1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
  11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
  21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
  31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
  41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
  51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
];

export const mockTransactions: transactionDetail[] = numTimes.map((num) : transactionDetail => ({
  amount: faker.finance.amount({min: 1, max: 100, symbol: "$"}),
  date: faker.date.past().toISOString().slice(0, 10),
  description: companies[Math.floor(Math.random() * companies.length)],
}));
